# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-25 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_auto_20200925_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='nomIntervenant',
            new_name='nom_intervenant',
        ),
    ]
