# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_auto_20200925_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
