# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-09-26 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_intervention_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervention',
            old_name='done',
            new_name='featured',
        ),
    ]
